version: '3.7'

services:
  server:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file: ./config/config.env
    networks:
      - app-network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge